[vk::binding(0, 0)]
internal Texture1D<float4> textures1DSampled[];

[vk::binding(1, 0)]
internal RWTexture1D<float4> textures1DStorage[];

[vk::binding(2, 0)]
internal Texture2D<float4> textures2DSampled[];

[vk::binding(3, 0)]
internal RWTexture2D<float4> textures2DStorage[];

[vk::binding(4, 0)]
internal Texture3D<float4> textures3DSampled[];

[vk::binding(5, 0)]
internal RWTexture3D<float4> textures3DStorage[];

[vk::binding(6, 0)]
internal TextureCube<float4> texturesCubeSampled[];

[vk::binding(7, 0)]
internal RWTexture2DArray<float4> texturesCubeStorage[];

[vk::binding(8, 0)]
internal SamplerState globalSamplers[];

[vk::binding(9, 0)]
internal StructuredBuffer<uint64_t> globalBufferAddresses;

public inline Texture1D<float4> GetReadOnlyTexture1D(uint index)
{
    return textures1DSampled[index];
}

public inline RWTexture1D<float4> GetReadWriteTexture1D(uint index)
{
    return textures1DStorage[index];
}

public inline Texture2D<float4> GetReadOnlyTexture2D(uint index)
{
    return textures2DSampled[index];
}

public inline RWTexture2D<float4> GetReadWriteTexture2D(uint index)
{
    return textures2DStorage[index];
}

public inline Texture3D<float4> GetReadOnlyTexture3D(uint index)
{
    return textures3DSampled[index];
}

public inline RWTexture3D<float4> GetReadWriteTexture3D(uint index)
{
    return textures3DStorage[index];
}

public inline TextureCube<float4> GetReadOnlyTextureCube(uint index)
{
    return texturesCubeSampled[index];
}

public inline RWTexture2DArray<float4> GetReadWriteTextureCube(uint index)
{
    return texturesCubeStorage[index];
}

public inline SamplerState GetSampler(uint index)
{
    return globalSamplers[index];
}

public inline T* GetBuffer<T>(uint slotIndex)
{
    return (T*)globalBufferAddresses[slotIndex];
}